name: Post Submit
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build and push images to quay.io/medik8s
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push version 0.0.1
        if: ${{ github.ref_type != 'tag' }}
        run: make docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push

      - name: Build and push versioned based on tag
        if: ${{ github.ref_type == 'tag' }}
        # remove leading 'v' from tag!
        run: export VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//') && make docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push
